[build]
  command   = "yarn build"
  publish   = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "netlify-plugin-cache-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "origin-when-cross-origin"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-DNS-Prefetch-Control = "on"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Permissions-Policy = ''' 
    camera=(),
    microphone=(),
    geolocation=()'''
    Content-Security-Policy = "default-src 'self';  script-src 'self' 'unsafe-eval' 'unsafe-inline' *.youtube.com *.twitter.com *.netlify.app *.netlify.com; child-src *.youtube.com *.google.com *.twitter.com *.netlify.app *.netlify.com *.codesandbox.io; style-src 'self' 'unsafe-inline' *.googleapis.com; img-src * blob: data:; media-src 'self' cdn.plyr.io d2xl4m2ghaywko.cloudfront.net; connect-src *; font-src 'self'"
  
[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
