packages:
  - '.'

allowBuilds:
  cypress: set this to true or false
  es5-ext: set this to true or false
  esbuild: set this to true or false
  playwright-webkit: set this to true or false
  sharp: set this to true or false

minimumReleaseAge: 10080
