name: Generates Snippet

on:
  repository_dispatch:
    types: [snippetify]

jobs:
  generate-snippet-entry:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        node: [12.x]
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node: ${{ matrix.node }}
      - name: Snippetify
        uses: ./.github/actions/gh-action-snippetify
        with:
          title: ${{ github.event.client_payload.title }}
          code: ${{ github.event.client_payload.code }}
          language: ${{ github.event.client_payload.language }}
          params: ${{ github.event.client_payload.params }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
